### ISSUE TITLE
Unhandled exeption when refreshing repos when no repo is selected

### ISSUE THREAD

**Issue by Aho-Senpai** [paissaheavyindustries/Triggernometry#51]
```System.NullReferenceException - Object reference not set to an instance of an object.
   at Triggernometry.CustomControls.UserInterface.UpdateRepository(TreeNode tnupdate)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Triggernometry.CustomControls.UserInterface, TriggernometryPlugin, Version=1.1.3.1, Culture=neutral, PublicKeyToken=null
```
After installing a repo and unchecking the readme, i had the possibility to hit refresh but nothing was selected, leading to that exeption

**Comment by paissaheavyindustries** [comment]
1.1.3.2
